travis:
  secure:
    BINSTAR_TOKEN: MCqoHSjTxzeh7SiOQDK4WCdMmtSt+2ok1nwnojIkADez2uOljNPfJVj8PhUOOZ9ListZXYAmQ5rJQb8lqZAy2VPvZAj1Xg73lAW/gWno/uuVKyZidZKCnJj5k4JY2GAOP/OAMgQL/8YxFZ68LwCcaazFXa0o1N98w6ImtoXkjCQ2QKmS5Mgpz3K+h7lkzWf7AcHvQ1vOJxpjpmmKan/LP50N3Hw5aZbZ10Iv/7+vYfAM2CXqtz0k4iRTzooyOYc/qNES8Tt5gs0XJvpveTpdEgHOvoCtkYZrMq7bAj2yoR3KAINdq7uBUfnqV6Ezkgn4J8bslq/+NhPu7PCdGjnRaqLVe7eOWQWBToNClfZsh+ex+lU464ctPnAMW4f0Mh2Damh7kP1+XGP67F0rIiOCywazR5W/XXvn9wIPEai4bHq9SZf63NZ9emrtDE+V7NnH5WLNnoHNqYdcH26hTfVI4nO3MCQWLIEteNyGwOL7TXY5O+iqoYcr6xQxC7ooV6aLxOTUbZFkNcuWk4ulNreX/WiXyFlwBZrcHyv9Bl5pY4n1NN1n19EzT83k1s/vi9jrwUJEhaGg2pvhdI/fmtxE/i6o3oiaZTvPseFWmtd6yeNxcp78G3pJtbFZ2xKZkoK30vgPsCD2U1eTbYzY3/SHwE+Xn3MM92YGwt1EbaXBnCk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
